package com.bwa3d.ambiprojector;

import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.LinearGradient;
import android.graphics.Matrix;
import android.graphics.Paint;
import android.graphics.Path;
import android.graphics.RadialGradient;
import android.graphics.RectF;
import android.graphics.Shader;
import android.os.SystemClock;
import android.view.GestureDetector;
import android.view.MotionEvent;
import android.view.View;

import androidx.annotation.NonNull;

/** Projection output with free TV quad, context zones, outer keystone and fast light renderers. */
public final class AmbilightView extends View {
    public interface GestureListener { void onSingleTap(); void onLongPress(); void onDoubleTap(); }
    public enum Zone { TOP, BOTTOM, LEFT, RIGHT }
    public enum ProjectionStyle { EDGE_GRADIENT, COLOR_CLOUD }
    private static final class Overlay { String text; long until; }

    private final Paint paint=new Paint(Paint.ANTI_ALIAS_FLAG|Paint.DITHER_FLAG);
    private final Paint bitmapPaint=new Paint(Paint.ANTI_ALIAS_FLAG|Paint.FILTER_BITMAP_FLAG);
    private final Paint textPaint=new Paint(Paint.ANTI_ALIAS_FLAG);
    private final GestureDetector gestures;
    private final Matrix keystoneMatrix=new Matrix();
    private final Path tvPath=new Path();
    private final float[] hsvScratch=new float[3];
    private final int[] cloudGradientColors=new int[5];
    private final float[] cloudGradientStops=new float[5];

    private volatile AmbilightState state=AmbilightState.black();
    private boolean debug=true;
    private GestureListener gestureListener;
    private final Overlay topOverlay=new Overlay(),bottomOverlay=new Overlay(),leftOverlay=new Overlay(),rightOverlay=new Overlay();

    private float outerFadeRatio=0.16f;
    private volatile float[] keystoneCorners={0f,0f,1f,0f,1f,1f,0f,1f};
    private volatile float[] tvQuad={0.20f,0.27f,0.80f,0.27f,0.80f,0.73f,0.20f,0.73f};
    private volatile float[][] textFrames={{0.24f,0.06f,0.76f,0.18f},{0.24f,0.82f,0.76f,0.94f},{0.03f,0.32f,0.18f,0.68f},{0.82f,0.32f,0.97f,0.68f}};

    private volatile ProjectionStyle projectionStyle=ProjectionStyle.COLOR_CLOUD;
    private float cloudSpread=0.42f,cloudRadius=0.26f,cloudOpacity=0.60f,cloudSaturation=1.32f,cloudBrightness=1.08f,cloudEdgePull=0.62f,cloudSoftness=0.72f,cornerBlend=0.82f,cornerRadius=1.48f;
    private float cloudDynamicAmount=0.85f,cloudDynamicRadius=0.65f,cloudDynamicStretch=0.85f,cloudDynamicOpacity=0.18f,cloudEnergyGamma=1.15f,cloudSaturationWeight=0.60f,cloudLumaWeight=0.40f;
    private float rgbGainR=1f,rgbGainG=1f,rgbGainB=1f;private int rgbOffsetR=0,rgbOffsetG=0,rgbOffsetB=0;
    private float cloudRenderScale=0.42f;private static final double CLOUD_PIXEL_BUDGET=420000.0;
    private Bitmap projectionBuffer,cloudBuffer;private Canvas projectionCanvas,cloudCanvas;

    public AmbilightView(Context context){super(context);setBackgroundColor(Color.BLACK);textPaint.setTypeface(android.graphics.Typeface.create("sans",android.graphics.Typeface.NORMAL));gestures=new GestureDetector(context,new GestureDetector.SimpleOnGestureListener(){@Override public boolean onDown(@NonNull MotionEvent e){return true;}@Override public boolean onSingleTapConfirmed(@NonNull MotionEvent e){if(gestureListener!=null)gestureListener.onSingleTap();return true;}@Override public void onLongPress(@NonNull MotionEvent e){if(gestureListener!=null)gestureListener.onLongPress();}@Override public boolean onDoubleTap(@NonNull MotionEvent e){if(gestureListener!=null)gestureListener.onDoubleTap();return true;}});}

    public void setGestureListener(GestureListener listener){gestureListener=listener;}public void setState(AmbilightState newState){if(newState==null)return;state=newState;postInvalidateOnAnimation();}public void setDebug(boolean enabled){debug=enabled;invalidate();}public boolean isDebug(){return debug;}
    public void setOuterFadeRatio(float v){outerFadeRatio=clamp(v,.02f,.42f);invalidate();}public float getOuterFadeRatio(){return outerFadeRatio;}public void setProjectionStyle(ProjectionStyle v){if(v!=null){projectionStyle=v;invalidate();}}public ProjectionStyle getProjectionStyle(){return projectionStyle;}
    public void setCloudSpread(float v){cloudSpread=clamp(v,.05f,.90f);invalidate();}public void setCloudRadius(float v){cloudRadius=clamp(v,.08f,.50f);invalidate();}public void setCloudOpacity(float v){cloudOpacity=clamp(v,.05f,1f);invalidate();}public void setCloudSaturation(float v){cloudSaturation=clamp(v,.50f,2.50f);invalidate();}public void setCloudBrightness(float v){cloudBrightness=clamp(v,.40f,1.80f);invalidate();}public void setCloudEdgePull(float v){cloudEdgePull=clamp(v,0f,1f);invalidate();}public void setCloudSoftness(float v){cloudSoftness=clamp(v,0f,1f);invalidate();}public void setCornerBlend(float v){cornerBlend=clamp(v,0f,1f);invalidate();}public void setCornerRadius(float v){cornerRadius=clamp(v,.70f,2.40f);invalidate();}
    public void setCloudDynamicAmount(float v){cloudDynamicAmount=clamp(v,0f,1.50f);invalidate();}public void setCloudDynamicRadius(float v){cloudDynamicRadius=clamp(v,0f,1.50f);invalidate();}public void setCloudDynamicStretch(float v){cloudDynamicStretch=clamp(v,0f,2f);invalidate();}public void setCloudDynamicOpacity(float v){cloudDynamicOpacity=clamp(v,0f,.80f);invalidate();}public void setCloudEnergyGamma(float v){cloudEnergyGamma=clamp(v,.40f,2.50f);invalidate();}public void setCloudSaturationWeight(float v){cloudSaturationWeight=clamp(v,0f,1f);invalidate();}public void setCloudLumaWeight(float v){cloudLumaWeight=clamp(v,0f,1f);invalidate();}public void setCloudRenderScale(float v){cloudRenderScale=clamp(v,.20f,1f);recycleCloudBuffer();invalidate();}
    public void setRgbCalibration(float r,float g,float b,int ro,int go,int bo){rgbGainR=clamp(r,.40f,2f);rgbGainG=clamp(g,.40f,2f);rgbGainB=clamp(b,.40f,2f);rgbOffsetR=clampInt(ro,-80,80);rgbOffsetG=clampInt(go,-80,80);rgbOffsetB=clampInt(bo,-80,80);invalidate();}
    public void setKeystoneCorners(float[] c){if(c==null||c.length!=8)return;float[] n=c.clone();for(int i=0;i<8;i++)n[i]=clamp(n[i],0f,1f);keystoneCorners=n;invalidate();}public float[] getKeystoneCorners(){return keystoneCorners.clone();}
    public void setTvQuad(float[] q){if(q==null||q.length!=8)return;float[] n=q.clone();for(int i=0;i<8;i++)n[i]=clamp(n[i],0f,1f);tvQuad=n;invalidate();}public float[] getTvQuad(){return tvQuad.clone();}
    public void setTvRect(float[] r){if(r==null||r.length!=4)return;float[] x=sanitizeRect(r.clone(),.08f);setTvQuad(new float[]{x[0],x[1],x[2],x[1],x[2],x[3],x[0],x[3]});}
    public void setTextFrames(float[][] f){if(f==null||f.length!=4)return;float[][] n=new float[4][4];for(int i=0;i<4;i++){if(f[i]==null||f[i].length!=4)return;n[i]=sanitizeRect(f[i].clone(),.04f);}textFrames=n;invalidate();}public float[][] getTextFrames(){float[][] n=new float[4][4];for(int i=0;i<4;i++)n[i]=textFrames[i].clone();return n;}

    public void showContextOverlay(String text,long durationMs){showContextOverlay(Zone.TOP,text,durationMs);}public void showContextOverlay(Zone zone,String text,long durationMs){Overlay o=overlay(zone);o.text=text;o.until=durationMs<=0?Long.MAX_VALUE:SystemClock.uptimeMillis()+durationMs;invalidate();}public void clearContextOverlay(Zone zone){Overlay o=overlay(zone);o.text=null;o.until=0;invalidate();}public void clearAllContextOverlays(){for(Zone z:Zone.values())clearContextOverlay(z);}public void showContextDemo(long d){showContextOverlay(Zone.TOP,"TOP · title / score / status",d);showContextOverlay(Zone.BOTTOM,"BOTTOM · subtitles / extra info",d);showContextOverlay(Zone.LEFT,"LEFT\ncontext\nzone",d);showContextOverlay(Zone.RIGHT,"RIGHT\nalerts\nzone",d);}private Overlay overlay(Zone z){switch(z){case BOTTOM:return bottomOverlay;case LEFT:return leftOverlay;case RIGHT:return rightOverlay;default:return topOverlay;}}

    @Override protected void onSizeChanged(int w,int h,int oldw,int oldh){super.onSizeChanged(w,h,oldw,oldh);recreateBuffer(w,h);}private void recreateBuffer(int w,int h){if(projectionBuffer!=null){projectionBuffer.recycle();projectionBuffer=null;projectionCanvas=null;}recycleCloudBuffer();if(w>0&&h>0){projectionBuffer=Bitmap.createBitmap(w,h,Bitmap.Config.ARGB_8888);projectionCanvas=new Canvas(projectionBuffer);}}private void recycleCloudBuffer(){if(cloudBuffer!=null){cloudBuffer.recycle();cloudBuffer=null;cloudCanvas=null;}}
    private void ensureCloudBuffer(int w,int h){if(w<=0||h<=0)return;double cap=Math.sqrt(CLOUD_PIXEL_BUDGET/Math.max(1.0,(double)w*h));float scale=clamp((float)Math.min(cloudRenderScale,cap),.18f,1f);int cw=Math.max(1,Math.min(w,Math.max(96,Math.round(w*scale)))),ch=Math.max(1,Math.min(h,Math.max(54,Math.round(h*scale))));if(cloudBuffer!=null&&cloudBuffer.getWidth()==cw&&cloudBuffer.getHeight()==ch)return;recycleCloudBuffer();cloudBuffer=Bitmap.createBitmap(cw,ch,Bitmap.Config.ARGB_8888);cloudCanvas=new Canvas(cloudBuffer);}

    @Override protected void onDraw(@NonNull Canvas canvas){super.onDraw(canvas);int w=getWidth(),h=getHeight();if(w<=0||h<=0)return;if(projectionBuffer==null||projectionBuffer.getWidth()!=w||projectionBuffer.getHeight()!=h)recreateBuffer(w,h);canvas.drawColor(Color.BLACK);if(projectionCanvas==null)return;projectionCanvas.drawColor(Color.BLACK);drawProjection(projectionCanvas,w,h);float[] k=keystoneCorners,src={0f,0f,w,0f,w,h,0f,h},dst={k[0]*w,k[1]*h,k[2]*w,k[3]*h,k[4]*w,k[5]*h,k[6]*w,k[7]*h};keystoneMatrix.reset();if(keystoneMatrix.setPolyToPoly(src,0,dst,0,4))canvas.drawBitmap(projectionBuffer,keystoneMatrix,bitmapPaint);else canvas.drawBitmap(projectionBuffer,0,0,bitmapPaint);}
    private void drawProjection(Canvas c,int w,int h){RectF tv=tvBounds(w,h);if(projectionStyle==ProjectionStyle.COLOR_CLOUD)drawColorCloudFast(c,w,h);else drawEdgeGradient(c,tv);drawOuterBlackVignette(c);drawTvBlackMask(c,w,h);drawContextFrames(c);if(debug)drawDebug(c,w,h);}
    private RectF tvBounds(int w,int h){float[] q=tvQuad,minmax={1f,1f,0f,0f};for(int i=0;i<8;i+=2){minmax[0]=Math.min(minmax[0],q[i]);minmax[2]=Math.max(minmax[2],q[i]);minmax[1]=Math.min(minmax[1],q[i+1]);minmax[3]=Math.max(minmax[3],q[i+1]);}return new RectF(minmax[0]*w,minmax[1]*h,minmax[2]*w,minmax[3]*h);}private Path buildTvPath(int w,int h){float[] q=tvQuad;tvPath.reset();tvPath.moveTo(q[0]*w,q[1]*h);tvPath.lineTo(q[2]*w,q[3]*h);tvPath.lineTo(q[4]*w,q[5]*h);tvPath.lineTo(q[6]*w,q[7]*h);tvPath.close();return tvPath;}private void drawTvBlackMask(Canvas c,int w,int h){paint.setShader(null);paint.setStyle(Paint.Style.FILL);paint.setColor(Color.BLACK);c.drawPath(buildTvPath(w,h),paint);}

    private void drawEdgeGradient(Canvas c,RectF tv){drawContinuousSides(c,tv);drawSmoothCorner(c,tv,true,true,edgeAverage(state.top,true),edgeAverage(state.left,true));drawSmoothCorner(c,tv,false,true,edgeAverage(state.top,false),edgeAverage(state.right,true));drawSmoothCorner(c,tv,true,false,edgeAverage(state.bottom,true),edgeAverage(state.left,false));drawSmoothCorner(c,tv,false,false,edgeAverage(state.bottom,false),edgeAverage(state.right,false));}
    private void drawColorCloudFast(Canvas target,int fullW,int fullH){ensureCloudBuffer(fullW,fullH);if(cloudCanvas==null||cloudBuffer==null)return;int rw=cloudBuffer.getWidth(),rh=cloudBuffer.getHeight();cloudCanvas.drawColor(Color.BLACK);drawColorCloud(cloudCanvas,tvBounds(rw,rh),rw,rh);paint.setShader(null);target.drawBitmap(cloudBuffer,null,new RectF(0f,0f,fullW,fullH),bitmapPaint);}
    private void drawColorCloud(Canvas c,RectF tv,int rw,int rh){AmbilightState s=state;float baseRadius=Math.max(10f,Math.min(rw,rh)*cloudRadius),sideRadius=baseRadius*(.76f+cloudSpread*.90f);drawHorizontalClouds(c,s.top,true,tv,sideRadius,7,rw,rh);drawHorizontalClouds(c,s.bottom,false,tv,sideRadius,7,rw,rh);drawVerticalClouds(c,s.left,true,tv,sideRadius,5,rw,rh);drawVerticalClouds(c,s.right,false,tv,sideRadius,5,rw,rh);int tlH=sampleWindow(s.top,0f,3),tlV=sampleWindow(s.left,0f,3),trH=sampleWindow(s.top,1f,3),trV=sampleWindow(s.right,0f,3),blH=sampleWindow(s.bottom,0f,3),blV=sampleWindow(s.left,1f,3),brH=sampleWindow(s.bottom,1f,3),brV=sampleWindow(s.right,1f,3);float cr=baseRadius*cornerRadius;drawCornerBridge(c,tv,true,true,tlH,tlV,cr,rw,rh);drawCornerBridge(c,tv,false,true,trH,trV,cr,rw,rh);drawCornerBridge(c,tv,true,false,blH,blV,cr,rw,rh);drawCornerBridge(c,tv,false,false,brH,brV,cr,rw,rh);}
    private void drawHorizontalClouds(Canvas c,int[] colors,boolean top,RectF tv,float radius,int count,int rw,int rh){if(colors==null||colors.length==0)return;float available=top?tv.top:rh-tv.bottom,pull=.82f-.67f*cloudEdgePull,baseCy=top?tv.top-available*pull:tv.bottom+available*pull,direction=top?-1f:1f;for(int i=0;i<count;i++){float t=count==1?.5f:i/(float)(count-1),cx=tv.left+tv.width()*t;int raw=sampleWindow(colors,t,2);float energy=cloudEnergy(raw);if(energy<.012f&&maxChannel(raw)<8)continue;int color=boostCloudColor(raw);drawCloudBlob(c,cx,baseCy+direction*available*dynamicReachOffset(energy),radius*dynamicRadiusScale(energy),color,.82f*dynamicOpacityScale(energy),1f,dynamicStretchScale(energy));}}
    private void drawVerticalClouds(Canvas c,int[] colors,boolean leftSide,RectF tv,float radius,int count,int rw,int rh){if(colors==null||colors.length==0)return;float available=leftSide?tv.left:rw-tv.right,pull=.82f-.67f*cloudEdgePull,baseCx=leftSide?tv.left-available*pull:tv.right+available*pull,direction=leftSide?-1f:1f;for(int i=0;i<count;i++){float t=count==1?.5f:i/(float)(count-1),cy=tv.top+tv.height()*t;int raw=sampleWindow(colors,t,2);float energy=cloudEnergy(raw);if(energy<.012f&&maxChannel(raw)<8)continue;int color=boostCloudColor(raw);drawCloudBlob(c,baseCx+direction*available*dynamicReachOffset(energy),cy,radius*dynamicRadiusScale(energy),color,.75f*dynamicOpacityScale(energy),dynamicStretchScale(energy),1f);}}
    private void drawCornerBridge(Canvas c,RectF tv,boolean leftSide,boolean topSide,int hc,int vc,float radius,int rw,int rh){float ax=leftSide?tv.left:rw-tv.right,ay=topSide?tv.top:rh-tv.bottom,sx=leftSide?-1f:1f,sy=topSide?-1f:1f,cx=leftSide?tv.left:tv.right,cy=topSide?tv.top:tv.bottom,sp=.82f-.67f*cloudEdgePull,dp=.60f-.40f*cloudEdgePull,sideX=cx+sx*ax*sp,sideY=cy+sy*ay*sp,centerX=cx+sx*ax*dp,centerY=cy+sy*ay*dp;int h=boostCloudColor(hc),v=boostCloudColor(vc),mr=mixWeighted(hc,vc,.5f),mixed=boostCloudColor(mr);float he=cloudEnergy(hc),ve=cloudEnergy(vc),ce=clamp(Math.max(he,ve)*.65f+(he+ve)*.175f,0f,1f);if(ce<.008f&&maxChannel(mr)<8)return;float reach=.5f*dynamicReachOffset(ce);centerX+=sx*ax*reach;centerY+=sy*ay*reach;drawCloudBlob(c,centerX,centerY,radius*dynamicRadiusScale(ce),mixed,(.34f+cornerBlend*.34f)*dynamicOpacityScale(ce),1f+(dynamicStretchScale(ce)-1f)*.72f,1f+(dynamicStretchScale(ce)-1f)*.72f);float hx=lerp(cx,centerX,.48f),hy=lerp(sideY,centerY,.54f),vx=lerp(sideX,centerX,.54f),vy=lerp(cy,centerY,.48f);if(he>.008f||maxChannel(hc)>=8)drawCloudBlob(c,hx,hy,radius*.88f*dynamicRadiusScale(he),h,(.24f+cornerBlend*.16f)*dynamicOpacityScale(he),1f,dynamicStretchScale(he));if(ve>.008f||maxChannel(vc)>=8)drawCloudBlob(c,vx,vy,radius*.88f*dynamicRadiusScale(ve),v,(.24f+cornerBlend*.16f)*dynamicOpacityScale(ve),dynamicStretchScale(ve),1f);}
    private void drawCloudBlob(Canvas c,float cx,float cy,float radius,int color,float strength,float sx,float sy){int alpha=Math.round(255f*cloudOpacity*clamp(strength,0f,1.45f));if(alpha<3||maxChannel(color)<5)return;float s=cloudSoftness;cloudGradientColors[0]=withAlpha(color,alpha);cloudGradientColors[1]=withAlpha(color,Math.round(alpha*lerp(.90f,.72f,s)));cloudGradientColors[2]=withAlpha(color,Math.round(alpha*lerp(.67f,.38f,s)));cloudGradientColors[3]=withAlpha(color,Math.round(alpha*lerp(.30f,.10f,s)));cloudGradientColors[4]=0;cloudGradientStops[0]=0f;cloudGradientStops[1]=lerp(.44f,.18f,s);cloudGradientStops[2]=lerp(.72f,.44f,s);cloudGradientStops[3]=lerp(.91f,.76f,s);cloudGradientStops[4]=1f;float r=Math.max(2f,radius);paint.setShader(new RadialGradient(cx,cy,r,cloudGradientColors,cloudGradientStops,Shader.TileMode.CLAMP));c.save();c.translate(cx,cy);c.scale(clamp(sx,.30f,4f),clamp(sy,.30f,4f));c.translate(-cx,-cy);c.drawCircle(cx,cy,r,paint);c.restore();}
    private float cloudEnergy(int color){int r=(color>>16)&255,g=(color>>8)&255,b=color&255,max=Math.max(r,Math.max(g,b)),min=Math.min(r,Math.min(g,b));float sat=max<=0?0f:(max-min)/(float)max,lum=clamp((.2126f*r+.7152f*g+.0722f*b)/255f,0f,1f),total=Math.max(.0001f,cloudSaturationWeight+cloudLumaWeight),raw=(sat*cloudSaturationWeight+lum*cloudLumaWeight)/total;return(float)Math.pow(clamp(raw,0f,1f),cloudEnergyGamma);}private float dynamicRadiusScale(float e){float a=cloudDynamicAmount*cloudDynamicRadius;return lerp(Math.max(.35f,1f-.55f*a),1f+a,clamp(e,0f,1f));}private float dynamicStretchScale(float e){float a=cloudDynamicAmount*cloudDynamicStretch;return lerp(Math.max(.35f,1f-.45f*a),1f+1.35f*a,clamp(e,0f,1f));}private float dynamicOpacityScale(float e){float a=cloudDynamicAmount*cloudDynamicOpacity;return lerp(Math.max(.55f,1f-.45f*a),1f+.55f*a,clamp(e,0f,1f));}private float dynamicReachOffset(float e){return(clamp(e,0f,1f)-.35f)*.10f*cloudDynamicAmount*cloudDynamicStretch;}
    private int sampleWindow(int[] src,float t,int hw){if(src==null||src.length==0)return Color.BLACK;int center=Math.round(clamp(t,0f,1f)*(src.length-1)),from=Math.max(0,center-hw),to=Math.min(src.length-1,center+hw),rs=0,gs=0,bs=0,n=0;for(int i=from;i<=to;i++){int c=src[i];rs+=(c>>16)&255;gs+=(c>>8)&255;bs+=c&255;n++;}return n==0?Color.BLACK:0xff000000|((rs/n)<<16)|((gs/n)<<8)|(bs/n);}private int boostCloudColor(int c){c=calibrateColor(c);Color.colorToHSV(c,hsvScratch);hsvScratch[1]=clamp(hsvScratch[1]*cloudSaturation,0f,1f);hsvScratch[2]=clamp(hsvScratch[2]*cloudBrightness,0f,1f);return Color.HSVToColor(hsvScratch);}private int maxChannel(int c){return Math.max((c>>16)&255,Math.max((c>>8)&255,c&255));}private int calibrateColor(int c){int r=clampInt(Math.round(((c>>16)&255)*rgbGainR)+rgbOffsetR,0,255),g=clampInt(Math.round(((c>>8)&255)*rgbGainG)+rgbOffsetG,0,255),b=clampInt(Math.round((c&255)*rgbGainB)+rgbOffsetB,0,255);return 0xff000000|(r<<16)|(g<<8)|b;}private int[] calibratedCopy(int[] src){int[] out=src.clone();for(int i=0;i<out.length;i++)out[i]=calibrateColor(out[i]);return out;}

    private void drawContinuousSides(Canvas c,RectF tv){int[] top=calibratedCopy(state.top),bottom=calibratedCopy(state.bottom),left=calibratedCopy(state.left),right=calibratedCopy(state.right);top=softCornerEnds(top,mix(edgeAverage(top,true,false),edgeAverage(left,true,false)),mix(edgeAverage(top,false,false),edgeAverage(right,true,false)));bottom=softCornerEnds(bottom,mix(edgeAverage(bottom,true,false),edgeAverage(left,false,false)),mix(edgeAverage(bottom,false,false),edgeAverage(right,false,false)));left=softCornerEnds(left,mix(edgeAverage(left,true,false),edgeAverage(top,true,false)),mix(edgeAverage(left,false,false),edgeAverage(bottom,true,false)));right=softCornerEnds(right,mix(edgeAverage(right,true,false),edgeAverage(top,false,false)),mix(edgeAverage(right,false,false),edgeAverage(bottom,false,false)));paint.setShader(new LinearGradient(tv.left,0,tv.right,0,top,positions(top.length),Shader.TileMode.CLAMP));c.drawRect(tv.left,0,tv.right,tv.top+1,paint);paint.setShader(new LinearGradient(tv.left,0,tv.right,0,bottom,positions(bottom.length),Shader.TileMode.CLAMP));c.drawRect(tv.left,tv.bottom-1,tv.right,getHeight(),paint);paint.setShader(new LinearGradient(0,tv.top,0,tv.bottom,left,positions(left.length),Shader.TileMode.CLAMP));c.drawRect(0,tv.top,tv.left+1,tv.bottom,paint);paint.setShader(new LinearGradient(0,tv.top,0,tv.bottom,right,positions(right.length),Shader.TileMode.CLAMP));c.drawRect(tv.right-1,tv.top,getWidth(),tv.bottom,paint);paint.setShader(new LinearGradient(0,0,0,tv.top,Color.BLACK,0,Shader.TileMode.CLAMP));c.drawRect(tv.left,0,tv.right,tv.top,paint);paint.setShader(new LinearGradient(0,tv.bottom,0,getHeight(),0,Color.BLACK,Shader.TileMode.CLAMP));c.drawRect(tv.left,tv.bottom,tv.right,getHeight(),paint);paint.setShader(new LinearGradient(0,0,tv.left,0,Color.BLACK,0,Shader.TileMode.CLAMP));c.drawRect(0,tv.top,tv.left,tv.bottom,paint);paint.setShader(new LinearGradient(tv.right,0,getWidth(),0,0,Color.BLACK,Shader.TileMode.CLAMP));c.drawRect(tv.right,tv.top,getWidth(),tv.bottom,paint);}
    private void drawSmoothCorner(Canvas c,RectF tv,boolean leftSide,boolean topSide,int hc,int vc){float x=leftSide?tv.left:tv.right,y=topSide?tv.top:tv.bottom,ex=leftSide?tv.left:getWidth()-tv.right,ey=topSide?tv.top:getHeight()-tv.bottom,r=Math.max(2f,(float)Math.hypot(ex,ey)*1.18f),sx=leftSide?1f:-1f,sy=topSide?1f:-1f;int mix=mix(hc,vc);drawSoftGlow(c,leftSide,topSide,x,y,r,mix,168);drawSoftGlow(c,leftSide,topSide,x+sx*ex*.20f,y,r*.92f,hc,92);drawSoftGlow(c,leftSide,topSide,x,y+sy*ey*.20f,r*.92f,vc,92);}private void drawSoftGlow(Canvas c,boolean leftSide,boolean topSide,float cx,float cy,float radius,int color,int alpha){paint.setShader(new RadialGradient(cx,cy,radius,new int[]{withAlpha(color,alpha),withAlpha(color,Math.round(alpha*.56f)),withAlpha(color,Math.round(alpha*.18f)),0},new float[]{0f,.30f,.66f,1f},Shader.TileMode.CLAMP));float l=leftSide?0f:Math.min(getWidth(),cx),r=leftSide?Math.max(0f,cx):getWidth(),t=topSide?0f:Math.min(getHeight(),cy),b=topSide?Math.max(0f,cy):getHeight();c.drawRect(l,t,r,b,paint);}private int edgeAverage(int[] src,boolean first){return edgeAverage(src,first,true);}private int edgeAverage(int[] src,boolean first,boolean calibrate){if(src==null||src.length==0)return Color.BLACK;int n=Math.min(4,src.length),rs=0,gs=0,bs=0;for(int i=0;i<n;i++){int idx=first?i:src.length-1-i,c=calibrate?calibrateColor(src[idx]):src[idx];rs+=(c>>16)&255;gs+=(c>>8)&255;bs+=c&255;}return 0xff000000|((rs/n)<<16)|((gs/n)<<8)|(bs/n);}private int[] softCornerEnds(int[] src,int first,int last){int[] out=src.clone();int n=Math.min(4,out.length);for(int i=0;i<n;i++){float s=(n-i)/(float)(n+1);out[i]=mixWeighted(out[i],first,s*.55f);int j=out.length-1-i;out[j]=mixWeighted(out[j],last,s*.55f);}return out;}
    private void drawOuterBlackVignette(Canvas c){float fw=Math.max(2f,getWidth()*outerFadeRatio),fh=Math.max(2f,getHeight()*outerFadeRatio);paint.setShader(new LinearGradient(0,0,fw,0,Color.BLACK,0,Shader.TileMode.CLAMP));c.drawRect(0,0,fw,getHeight(),paint);paint.setShader(new LinearGradient(getWidth()-fw,0,getWidth(),0,0,Color.BLACK,Shader.TileMode.CLAMP));c.drawRect(getWidth()-fw,0,getWidth(),getHeight(),paint);paint.setShader(new LinearGradient(0,0,0,fh,Color.BLACK,0,Shader.TileMode.CLAMP));c.drawRect(0,0,getWidth(),fh,paint);paint.setShader(new LinearGradient(0,getHeight()-fh,0,getHeight(),0,Color.BLACK,Shader.TileMode.CLAMP));c.drawRect(0,getHeight()-fh,getWidth(),getHeight(),paint);}
    private void drawContextFrames(Canvas c){long now=SystemClock.uptimeMillis();Overlay[] a={topOverlay,bottomOverlay,leftOverlay,rightOverlay};float[][] f=textFrames;textPaint.setColor(Color.WHITE);textPaint.setShadowLayer(10f,0f,2f,Color.BLACK);for(int i=0;i<4;i++)if(alive(a[i],now))drawTextInFrame(c,a[i].text,f[i]);textPaint.clearShadowLayer();if(isAnyOverlayAlive(now))postInvalidateDelayed(200);}private void drawTextInFrame(Canvas c,String text,float[] nr){if(text==null)return;RectF r=new RectF(nr[0]*getWidth(),nr[1]*getHeight(),nr[2]*getWidth(),nr[3]*getHeight());float maxSize=Math.max(12f,Math.min(r.height()*.34f,getHeight()*.045f));textPaint.setTextSize(maxSize);textPaint.setTextAlign(Paint.Align.CENTER);String[] lines=text.split("\\n");float line=textPaint.getTextSize()*1.18f,y=r.centerY()-(lines.length-1)*line*.5f-(textPaint.ascent()+textPaint.descent())*.5f;for(String s:lines){String d=ellipsize(s,r.width()*.92f);c.drawText(d,r.centerX(),y,textPaint);y+=line;}}private String ellipsize(String s,float maxW){if(textPaint.measureText(s)<=maxW)return s;String out=s;while(out.length()>2&&textPaint.measureText(out+"…")>maxW)out=out.substring(0,out.length()-1);return out+"…";}private boolean alive(Overlay o,long now){if(o.text==null||now>o.until){o.text=null;return false;}return true;}private boolean isAnyOverlayAlive(long now){return alive(topOverlay,now)||alive(bottomOverlay,now)||alive(leftOverlay,now)||alive(rightOverlay,now);}
    private void drawDebug(Canvas c,int w,int h){paint.setShader(null);paint.setStyle(Paint.Style.STROKE);paint.setStrokeWidth(3f);paint.setColor(0xaa60ff9c);c.drawPath(buildTvPath(w,h),paint);paint.setStyle(Paint.Style.FILL);textPaint.setTextAlign(Paint.Align.LEFT);textPaint.setTextSize(Math.max(15f,getHeight()*.022f));textPaint.setColor(Color.WHITE);float x=18f,y=28f,line=textPaint.getTextSize()*1.35f;c.drawText("Ambi Projector v0.21 · "+(projectionStyle==ProjectionStyle.COLOR_CLOUD?"FAST CLOUD":"EDGE"),x,y,textPaint);y+=line;c.drawText(String.format(java.util.Locale.US,"Network source: %dx%d   %.1f fps",state.sourceWidth,state.sourceHeight,state.fps),x,y,textPaint);y+=line;c.drawText("TV mask: free quad · Text zones: API/drag",x,y,textPaint);}

    private float[] positions(int n){float[] p=new float[n];if(n==1){p[0]=0f;return p;}for(int i=0;i<n;i++)p[i]=i/(float)(n-1);return p;}private float lerp(float a,float b,float t){return a+(b-a)*t;}private int mix(int a,int b){return mixWeighted(a,b,.5f);}private int mixWeighted(int a,int b,float wb){wb=clamp(wb,0f,1f);float wa=1f-wb;int r=Math.round(((a>>16)&255)*wa+((b>>16)&255)*wb),g=Math.round(((a>>8)&255)*wa+((b>>8)&255)*wb),bl=Math.round((a&255)*wa+(b&255)*wb);return 0xff000000|(r<<16)|(g<<8)|bl;}private int withAlpha(int c,int a){return(clampInt(a,0,255)<<24)|(c&0xffffff);}private float[] sanitizeRect(float[] r,float min){r[0]=clamp(r[0],0f,.98f);r[1]=clamp(r[1],0f,.98f);r[2]=clamp(r[2],.02f,1f);r[3]=clamp(r[3],.02f,1f);if(r[2]-r[0]<min)r[2]=Math.min(1f,r[0]+min);if(r[3]-r[1]<min)r[3]=Math.min(1f,r[1]+min);if(r[2]-r[0]<min)r[0]=Math.max(0f,r[2]-min);if(r[3]-r[1]<min)r[1]=Math.max(0f,r[3]-min);return r;}@Override public boolean onTouchEvent(MotionEvent e){return gestures.onTouchEvent(e)||super.onTouchEvent(e);}private static float clamp(float v,float lo,float hi){return Math.max(lo,Math.min(hi,v));}private static int clampInt(int v,int lo,int hi){return Math.max(lo,Math.min(hi,v));}
}
