package com.bwa3d.ambiprojector;

import android.content.SharedPreferences;

import org.json.JSONObject;

import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.Inet4Address;
import java.net.InetAddress;
import java.net.InetSocketAddress;
import java.net.NetworkInterface;
import java.net.ServerSocket;
import java.net.Socket;
import java.net.URLDecoder;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

/** Unified phone portal/API for TV Source + Projector, free geometry and contextual text zones. */
public final class ProjectorWebServer {
    public interface Listener {
        void onSettingsChanged();
        void onSourceChanged(String source);
        void onTextZone(int zone,String text,long durationMs);
    }

    public static final int PORT = 8081;
    private static final int SOURCE_PORT = 8080;
    private final SharedPreferences prefs;
    private final Listener listener;
    private final ExecutorService pool = Executors.newFixedThreadPool(6);
    private final String[] zoneText={"","","",""};
    private final long[] zoneUntil={0,0,0,0};
    private volatile boolean running;
    private ServerSocket server;
    private String url = "http://127.0.0.1:" + PORT;

    public ProjectorWebServer(SharedPreferences prefs, Listener listener) { this.prefs = prefs; this.listener = listener; }

    public synchronized String start() throws IOException {
        if (running) return url;
        server = new ServerSocket(PORT, 16, InetAddress.getByName("0.0.0.0"));server.setReuseAddress(true);running = true;
        List<String> ips = localIpv4Addresses();if (!ips.isEmpty()) url = "http://" + ips.get(0) + ":" + PORT;pool.execute(this::acceptLoop);return url;
    }
    public synchronized void stop() {running=false;if(server!=null)try{server.close();}catch(IOException ignored){}pool.shutdownNow();}
    public String getUrl() { return url; }

    private void acceptLoop(){while(running){try{Socket s=server.accept();s.setTcpNoDelay(true);s.setSoTimeout(3000);pool.execute(()->handle(s));}catch(IOException ignored){if(!running)break;}}}

    private void handle(Socket socket){
        try{
            BufferedInputStream in=new BufferedInputStream(socket.getInputStream());String line=readLine(in);if(line==null)return;String[] first=line.split(" ");String method=first.length>0?first[0]:"GET",raw=first.length>1?first[1]:"/";
            Map<String,String> headers=new HashMap<>();while((line=readLine(in))!=null&&line.length()>0){int p=line.indexOf(':');if(p>0)headers.put(line.substring(0,p).trim().toLowerCase(Locale.US),line.substring(p+1).trim());}
            String body="";int len=intValue(headers.get("content-length"),0);if(len>0&&len<=65536)body=new String(readExactly(in,len),StandardCharsets.UTF_8);
            String path=raw,query="";int q=raw.indexOf('?');if(q>=0){path=raw.substring(0,q);query=raw.substring(q+1);}Map<String,String> params=parseQuery(query);mergeBody(params,body,headers.get("content-type"));
            if("OPTIONS".equalsIgnoreCase(method)){send(socket,"text/plain",new byte[0]);return;}
            if("/api/settings".equals(path)){applyProjector(params);sendJson(socket,settingsJson());}
            else if("/api/status".equals(path))sendJson(socket,settingsJson());
            else if("/api/source/status".equals(path))sendJson(socket,proxySource("/api/status"));
            else if("/api/source/settings".equals(path)){String suffix=params.isEmpty()?"":"?"+encodeQuery(params);sendJson(socket,proxySource("/api/settings"+suffix));}
            else if("/api/source/capture/latest".equals(path))sendJson(socket,proxySource("/api/capture/latest"));
            else if("/api/source/snapshot.jpg".equals(path)){byte[] jpg=proxySourceBytes("/api/capture/snapshot.jpg");if(jpg==null)sendStatus(socket,502,"text/plain; charset=utf-8","TV snapshot unavailable\n".getBytes(StandardCharsets.UTF_8));else send(socket,"image/jpeg",jpg);}
            else if("/api/text-zones".equals(path))sendJson(socket,textZonesJson());
            else if("/api/text-zone".equals(path)){applyTextZone(params);sendJson(socket,textZonesJson());}
            else if("/api/text-zones/clear".equals(path)){clearTextZones();sendJson(socket,textZonesJson());}
            else if("/health".equals(path))send(socket,"text/plain; charset=utf-8","OK AmbiP Control Center v0.21\n".getBytes(StandardCharsets.UTF_8));
            else send(socket,"text/html; charset=utf-8",PAGE.getBytes(StandardCharsets.UTF_8));
        }catch(Throwable ignored){}finally{try{socket.close();}catch(IOException ignored){}}
    }

    private void applyProjector(Map<String,String> q){
        SharedPreferences.Editor e=prefs.edit();String source=q.get("source");if(source!=null)e.putString("networkTvSource",source.trim());String style=q.get("style");if(style!=null)e.putString("projectionStyle","EDGE_GRADIENT".equals(style)?"EDGE_GRADIENT":"COLOR_CLOUD");
        putFloat(e,q,"smooth","networkSmoothing",0f,.85f);putBoolean(e,q,"interp","interpolationEnabled");putInt(e,q,"interpms","interpolationMs",0,140);putFloat(e,q,"adaptive","interpolationAdaptive",0f,1f);putInt(e,q,"hz","interpolationHz",30,120);
        putFloat(e,q,"brightness","cloudBrightness",.40f,1.80f);putFloat(e,q,"saturation","cloudSaturation",.50f,2.50f);putFloat(e,q,"spread","cloudSpread",.05f,.90f);putFloat(e,q,"radius","cloudRadius",.08f,.50f);putFloat(e,q,"opacity","cloudOpacity",.05f,1f);putFloat(e,q,"edgepull","cloudEdgePull",0f,1f);putFloat(e,q,"softness","cloudSoftness",0f,1f);putFloat(e,q,"cornerblend","cornerBlend",0f,1f);putFloat(e,q,"cornerradius","cornerRadius",.70f,2.40f);putFloat(e,q,"dynamic","cloudDynamicAmount",0f,1.50f);putFloat(e,q,"dynradius","cloudDynamicRadius",0f,1.50f);putFloat(e,q,"stretch","cloudDynamicStretch",0f,2f);putFloat(e,q,"dynopacity","cloudDynamicOpacity",0f,.80f);putFloat(e,q,"energygamma","cloudEnergyGamma",.40f,2.50f);putFloat(e,q,"satweight","cloudSaturationWeight",0f,1f);putFloat(e,q,"lumaweight","cloudLumaWeight",0f,1f);putFloat(e,q,"fade","outerFade",.02f,.42f);putFloat(e,q,"cloudscale","cloudRenderScale",.20f,1f);
        putFloat(e,q,"rgain","rgbGainR",.40f,2f);putFloat(e,q,"ggain","rgbGainG",.40f,2f);putFloat(e,q,"bgain","rgbGainB",.40f,2f);putInt(e,q,"roff","rgbOffsetR",-80,80);putInt(e,q,"goff","rgbOffsetG",-80,80);putInt(e,q,"boff","rgbOffsetB",-80,80);
        for(int i=0;i<8;i++){putFloat(e,q,"k"+i,"keystone"+i,0f,1f);putFloat(e,q,"tq"+i,"tvQuad"+i,0f,1f);}putBoolean(e,q,"calibrate","calibrationOverlay");for(int z=0;z<4;z++)for(int i=0;i<4;i++)putFloat(e,q,"tf"+z+"_"+i,"textFrame"+z+"_"+i,0f,1f);
        // Legacy rectangle API stays accepted and is converted to a quad.
        if(q.containsKey("tv0")||q.containsKey("tv1")||q.containsKey("tv2")||q.containsKey("tv3")){float l=floatValue(q.get("tv0"),prefs.getFloat("tvQuad0",.20f)),t=floatValue(q.get("tv1"),prefs.getFloat("tvQuad1",.27f)),r=floatValue(q.get("tv2"),prefs.getFloat("tvQuad2",.80f)),b=floatValue(q.get("tv3"),prefs.getFloat("tvQuad5",.73f));e.putFloat("tvQuad0",clamp(l,0f,1f)).putFloat("tvQuad1",clamp(t,0f,1f)).putFloat("tvQuad2",clamp(r,0f,1f)).putFloat("tvQuad3",clamp(t,0f,1f)).putFloat("tvQuad4",clamp(r,0f,1f)).putFloat("tvQuad5",clamp(b,0f,1f)).putFloat("tvQuad6",clamp(l,0f,1f)).putFloat("tvQuad7",clamp(b,0f,1f));}
        e.apply();sanitizeTextFrames();if(listener!=null){listener.onSettingsChanged();if(source!=null)listener.onSourceChanged(source.trim());}
    }

    private void applyTextZone(Map<String,String> q){
        int zone=parseZone(q.get("zone"));if(zone<0||zone>3)return;SharedPreferences.Editor e=prefs.edit();String[] names={"l","t","r","b"};for(int i=0;i<4;i++)putFloat(e,q,names[i],"textFrame"+zone+"_"+i,0f,1f);e.apply();sanitizeTextFrames();
        boolean clear=truthy(q.get("clear"));String text=clear?null:q.get("text");long duration=longValue(q.get("durationMs"),5000L);if(duration<0)duration=0;if(duration>86400000L)duration=86400000L;
        if(clear){zoneText[zone]="";zoneUntil[zone]=0;}else if(text!=null){zoneText[zone]=text;zoneUntil[zone]=duration==0?Long.MAX_VALUE:System.currentTimeMillis()+duration;}
        if(listener!=null){listener.onSettingsChanged();if(clear||text!=null)listener.onTextZone(zone,text,duration);}
    }
    private void clearTextZones(){for(int z=0;z<4;z++){zoneText[z]="";zoneUntil[z]=0;if(listener!=null)listener.onTextZone(z,null,0);}}
    private int parseZone(String s){if(s==null)return-1;String x=s.trim().toLowerCase(Locale.US);if("top".equals(x))return 0;if("bottom".equals(x))return 1;if("left".equals(x))return 2;if("right".equals(x))return 3;return intValue(x,-1);}

    private void sanitizeTextFrames(){float[][] d={{.24f,.06f,.76f,.18f},{.24f,.82f,.76f,.94f},{.03f,.32f,.18f,.68f},{.82f,.32f,.97f,.68f}};SharedPreferences.Editor e=prefs.edit();for(int z=0;z<4;z++){float l=prefs.getFloat("textFrame"+z+"_0",d[z][0]),t=prefs.getFloat("textFrame"+z+"_1",d[z][1]),r=prefs.getFloat("textFrame"+z+"_2",d[z][2]),b=prefs.getFloat("textFrame"+z+"_3",d[z][3]);if(r-l<.04f)r=Math.min(1f,l+.04f);if(b-t<.04f)b=Math.min(1f,t+.04f);if(r-l<.04f)l=Math.max(0f,r-.04f);if(b-t<.04f)t=Math.max(0f,b-.04f);e.putFloat("textFrame"+z+"_0",l).putFloat("textFrame"+z+"_1",t).putFloat("textFrame"+z+"_2",r).putFloat("textFrame"+z+"_3",b);}e.apply();}

    private String proxySource(String sourcePath){Endpoint ep=endpoint(prefs.getString("networkTvSource",""));if(ep==null)return"{\"reachable\":false,\"error\":\"TV Source address not configured\"}";long started=System.nanoTime();try{byte[] body=rawHttpGetBytes(ep,sourcePath);long rtt=Math.max(0L,Math.round((System.nanoTime()-started)/1_000_000.0));String trimmed=body==null?"":new String(body,StandardCharsets.UTF_8).trim();if(trimmed.isEmpty())trimmed="{}";return"{\"reachable\":true,\"rttMs\":"+rtt+",\"data\":"+trimmed+"}";}catch(Throwable t){return"{\"reachable\":false,\"error\":\""+escape(t.getClass().getSimpleName())+"\"}";}}
    private byte[] proxySourceBytes(String path){Endpoint ep=endpoint(prefs.getString("networkTvSource",""));if(ep==null)return null;try{return rawHttpGetBytes(ep,path);}catch(Throwable t){return null;}}
    private static byte[] rawHttpGetBytes(Endpoint ep,String path)throws IOException{Socket s=new Socket();try{s.connect(new InetSocketAddress(ep.host,ep.port),650);s.setSoTimeout(1800);s.setTcpNoDelay(true);OutputStream out=s.getOutputStream();String request="GET "+path+" HTTP/1.1\r\nHost: "+ep.host+"\r\nConnection: close\r\nCache-Control: no-cache\r\n\r\n";out.write(request.getBytes(StandardCharsets.US_ASCII));out.flush();BufferedInputStream in=new BufferedInputStream(s.getInputStream());String status=readLine(in);if(status==null||!status.contains(" 200 "))throw new IOException("HTTP response: "+status);String line;while((line=readLine(in))!=null&&line.length()>0){}ByteArrayOutputStream body=new ByteArrayOutputStream(4096);byte[] buf=new byte[2048];int n,total=0;while((n=in.read(buf))>=0){if(n==0)continue;body.write(buf,0,n);total+=n;if(total>512000)break;}return body.toByteArray();}finally{try{s.close();}catch(IOException ignored){}}}
    private static Endpoint endpoint(String raw){if(raw==null)return null;String s=raw.trim();if(s.isEmpty())return null;int scheme=s.indexOf("://");if(scheme>=0)s=s.substring(scheme+3);int slash=s.indexOf('/');if(slash>=0)s=s.substring(0,slash);int port=SOURCE_PORT;String host=s;int colon=s.lastIndexOf(':');if(colon>0&&s.indexOf(':')==colon){try{port=Integer.parseInt(s.substring(colon+1));host=s.substring(0,colon);}catch(Exception ignored){}}return host.isEmpty()?null:new Endpoint(host,port);}
    private static final class Endpoint{final String host;final int port;Endpoint(String h,int p){host=h;port=p;}}

    private String settingsJson(){StringBuilder s=new StringBuilder(3600);s.append('{');s.append("\"source\":\"").append(escape(prefs.getString("networkTvSource",""))).append("\",");s.append("\"style\":\"").append(escape(prefs.getString("projectionStyle","COLOR_CLOUD"))).append("\",");
        s.append("\"smooth\":").append(f(prefs.getFloat("networkSmoothing",.12f))).append(',').append("\"interp\":").append(prefs.getBoolean("interpolationEnabled",true)).append(',').append("\"interpms\":").append(prefs.getInt("interpolationMs",30)).append(',').append("\"adaptive\":").append(f(prefs.getFloat("interpolationAdaptive",.94f))).append(',').append("\"hz\":").append(prefs.getInt("interpolationHz",60)).append(',');
        String[] ck={"brightness","saturation","spread","radius","opacity","edgepull","softness","cornerblend","cornerradius","dynamic","dynradius","stretch","dynopacity","energygamma","satweight","lumaweight","fade","cloudscale"};String[] cp={"cloudBrightness","cloudSaturation","cloudSpread","cloudRadius","cloudOpacity","cloudEdgePull","cloudSoftness","cornerBlend","cornerRadius","cloudDynamicAmount","cloudDynamicRadius","cloudDynamicStretch","cloudDynamicOpacity","cloudEnergyGamma","cloudSaturationWeight","cloudLumaWeight","outerFade","cloudRenderScale"};float[] cd={1.08f,1.32f,.42f,.26f,.60f,.62f,.72f,.82f,1.48f,.85f,.65f,.85f,.18f,1.15f,.60f,.40f,.16f,.42f};for(int i=0;i<ck.length;i++)s.append('\"').append(ck[i]).append("\":").append(f(prefs.getFloat(cp[i],cd[i]))).append(',');
        s.append("\"rgain\":").append(f(prefs.getFloat("rgbGainR",1f))).append(',').append("\"ggain\":").append(f(prefs.getFloat("rgbGainG",1f))).append(',').append("\"bgain\":").append(f(prefs.getFloat("rgbGainB",1f))).append(',').append("\"roff\":").append(prefs.getInt("rgbOffsetR",0)).append(',').append("\"goff\":").append(prefs.getInt("rgbOffsetG",0)).append(',').append("\"boff\":").append(prefs.getInt("rgbOffsetB",0)).append(',');
        float[] kd={0,0,1,0,1,1,0,1},td={.20f,.27f,.80f,.27f,.80f,.73f,.20f,.73f};for(int i=0;i<8;i++){s.append("\"k").append(i).append("\":").append(f(prefs.getFloat("keystone"+i,kd[i]))).append(',');s.append("\"tq").append(i).append("\":").append(f(prefs.getFloat("tvQuad"+i,td[i]))).append(',');}
        float[][] d={{.24f,.06f,.76f,.18f},{.24f,.82f,.76f,.94f},{.03f,.32f,.18f,.68f},{.82f,.32f,.97f,.68f}};for(int z=0;z<4;z++)for(int i=0;i<4;i++)s.append("\"tf").append(z).append('_').append(i).append("\":").append(f(prefs.getFloat("textFrame"+z+"_"+i,d[z][i]))).append(',');s.append("\"calibrate\":").append(prefs.getBoolean("calibrationOverlay",false)).append('}');return s.toString();}
    private String textZonesJson(){String[] names={"top","bottom","left","right"};StringBuilder s=new StringBuilder(1200).append("{\"zones\":[");long now=System.currentTimeMillis();float[][] d={{.24f,.06f,.76f,.18f},{.24f,.82f,.76f,.94f},{.03f,.32f,.18f,.68f},{.82f,.32f,.97f,.68f}};for(int z=0;z<4;z++){if(z>0)s.append(',');String text=(zoneUntil[z]>0&&(zoneUntil[z]==Long.MAX_VALUE||zoneUntil[z]>=now))?zoneText[z]:"";s.append("{\"zone\":\"").append(names[z]).append("\",\"text\":\"").append(escape(text)).append("\",\"box\":[");for(int i=0;i<4;i++){if(i>0)s.append(',');s.append(f(prefs.getFloat("textFrame"+z+"_"+i,d[z][i])));}s.append("]}");}return s.append("]}").toString();}

    private static void mergeBody(Map<String,String> out,String body,String contentType){if(body==null||body.isEmpty())return;try{if(contentType!=null&&contentType.toLowerCase(Locale.US).contains("application/json")){JSONObject o=new JSONObject(body);Iterator<String> keys=o.keys();while(keys.hasNext()){String k=keys.next();Object v=o.opt(k);out.put(k,v==null?"":String.valueOf(v));}}else out.putAll(parseQuery(body));}catch(Exception ignored){}}
    private static String encodeQuery(Map<String,String> q){StringBuilder s=new StringBuilder();for(Map.Entry<String,String> e:q.entrySet()){if(s.length()>0)s.append('&');s.append(urlEncode(e.getKey())).append('=').append(urlEncode(e.getValue()));}return s.toString();}
    private static String urlEncode(String v){try{return java.net.URLEncoder.encode(v==null?"":v,"UTF-8");}catch(Exception e){return"";}}
    private static void putFloat(SharedPreferences.Editor e,Map<String,String> q,String key,String pref,float lo,float hi){String s=q.get(key);if(s==null)return;try{e.putFloat(pref,clamp(Float.parseFloat(s),lo,hi));}catch(Exception ignored){}}
    private static void putInt(SharedPreferences.Editor e,Map<String,String> q,String key,String pref,int lo,int hi){String s=q.get(key);if(s==null)return;try{e.putInt(pref,Math.max(lo,Math.min(hi,Integer.parseInt(s))));}catch(Exception ignored){}}
    private static void putBoolean(SharedPreferences.Editor e,Map<String,String> q,String key,String pref){String s=q.get(key);if(s!=null)e.putBoolean(pref,truthy(s));}
    private static boolean truthy(String s){return s!=null&&("1".equals(s)||"true".equalsIgnoreCase(s)||"on".equalsIgnoreCase(s));}
    private static int intValue(String s,int d){try{return s==null?d:Integer.parseInt(s);}catch(Exception e){return d;}}
    private static long longValue(String s,long d){try{return s==null?d:Long.parseLong(s);}catch(Exception e){return d;}}
    private static float floatValue(String s,float d){try{return s==null?d:Float.parseFloat(s);}catch(Exception e){return d;}}
    private static float clamp(float v,float lo,float hi){return Math.max(lo,Math.min(hi,v));}
    private static String f(float v){return String.format(Locale.US,"%.4f",v);}private static String escape(String s){if(s==null)return"";return s.replace("\\","\\\\").replace("\"","\\\"").replace("\n","\\n").replace("\r","");}
    private static Map<String,String> parseQuery(String query){Map<String,String> out=new HashMap<>();if(query==null)return out;for(String p:query.split("&")){if(p.isEmpty())continue;int x=p.indexOf('=');String k=x<0?p:p.substring(0,x),v=x<0?"":p.substring(x+1);try{out.put(URLDecoder.decode(k,"UTF-8"),URLDecoder.decode(v,"UTF-8"));}catch(Exception ignored){}}return out;}
    private static byte[] readExactly(InputStream in,int len)throws IOException{byte[] b=new byte[len];int o=0;while(o<len){int n=in.read(b,o,len-o);if(n<0)throw new IOException("EOF");o+=n;}return b;}
    private static String readLine(InputStream in)throws IOException{ByteArrayOutputStream b=new ByteArrayOutputStream();int c;boolean cr=false;while((c=in.read())>=0){if(cr&&c=='\n')break;if(cr){b.write('\r');cr=false;}if(c=='\r')cr=true;else b.write(c);if(b.size()>16384)break;}if(c<0&&b.size()==0)return null;return new String(b.toByteArray(),StandardCharsets.UTF_8);}
    private static void sendJson(Socket s,String json)throws IOException{send(s,"application/json; charset=utf-8",json.getBytes(StandardCharsets.UTF_8));}
    private static void send(Socket s,String type,byte[] body)throws IOException{sendStatus(s,200,type,body);}
    private static void sendStatus(Socket s,int code,String type,byte[] body)throws IOException{BufferedOutputStream out=new BufferedOutputStream(s.getOutputStream());String reason=code==200?"OK":code==502?"Bad Gateway":"Error";String h="HTTP/1.1 "+code+" "+reason+"\r\nContent-Type: "+type+"\r\nContent-Length: "+body.length+"\r\nCache-Control: no-store\r\nAccess-Control-Allow-Origin: *\r\nAccess-Control-Allow-Methods: GET,POST,OPTIONS\r\nAccess-Control-Allow-Headers: Content-Type\r\nConnection: close\r\n\r\n";out.write(h.getBytes(StandardCharsets.US_ASCII));out.write(body);out.flush();}
    private static List<String> localIpv4Addresses(){List<String[]> found=new ArrayList<>();try{for(NetworkInterface ni:Collections.list(NetworkInterface.getNetworkInterfaces())){if(!ni.isUp()||ni.isLoopback())continue;String name=ni.getName()==null?"":ni.getName().toLowerCase(Locale.US);if(name.startsWith("tun")||name.startsWith("rmnet"))continue;for(InetAddress a:Collections.list(ni.getInetAddresses())){if(!(a instanceof Inet4Address)||a.isLoopbackAddress()||a.isLinkLocalAddress())continue;int score=(name.startsWith("wlan")||name.startsWith("wifi"))?0:(name.startsWith("eth")?1:2);found.add(new String[]{String.valueOf(score),a.getHostAddress()});}}}catch(Throwable ignored){}Collections.sort(found,new Comparator<String[]>(){@Override public int compare(String[] a,String[] b){return Integer.compare(Integer.parseInt(a[0]),Integer.parseInt(b[0]));}});List<String> out=new ArrayList<>();for(String[] x:found)if(x[1]!=null&&!out.contains(x[1]))out.add(x[1]);return out;}

    private static final String PAGE="""
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1"><title>AmbiP Control Center</title><style>
*{box-sizing:border-box}body{background:#090b0e;color:#eee;font-family:system-ui,sans-serif;max-width:980px;margin:auto;padding:16px}.card{background:#15191f;padding:16px;border-radius:14px;margin:12px 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}input[type=range]{width:100%}.text,textarea,select{padding:10px;width:100%;background:#222831;color:#fff;border:1px solid #39434f;border-radius:8px}.v{float:right;color:#9fd}.note{color:#9ba6b4;font-size:13px}.toggle{width:auto}.pill{display:inline-block;padding:5px 9px;border-radius:999px;background:#272e38;margin-right:6px}.ok{background:#173d29;color:#9ff0bc}.bad{background:#4b2424;color:#ffb3b3}button{background:#28313c;color:#fff;border:1px solid #465362;border-radius:9px;padding:10px 13px;margin:3px}#geom{width:100%;background:#080b10;border:1px solid #39434f;border-radius:12px;touch-action:none}.outer{fill:rgba(40,199,255,.04);stroke:#28c7ff;stroke-width:4}.tv{fill:rgba(96,255,156,.06);stroke:#60ff9c;stroke-width:4}.handleO{fill:#28c7ff;stroke:#fff;stroke-width:3}.handleT{fill:#60ff9c;stroke:#fff;stroke-width:3}.textBox{fill:rgba(255,183,77,.09);stroke:#ffb74d;stroke-width:3;stroke-dasharray:9 5;cursor:move}.handleX{fill:#ffb74d;stroke:#fff;stroke-width:2}.label{fill:#fff;font-size:22px;pointer-events:none}.guide{stroke:#29313a;stroke-width:1}.api{background:#0d1117;padding:10px;border-radius:8px;white-space:pre-wrap;word-break:break-word;font:12px monospace;color:#b8c7d9}h2,h3{margin:5px 0 12px}@media(max-width:650px){.grid{grid-template-columns:1fr}}
</style></head><body>
<h2>AmbiP Control Center · v0.21</h2><div><span id="pb" class="pill">Projector</span><span id="tb" class="pill">TV Source</span><span id="rtt" class="pill">—</span></div>
<div class="card"><h3>Connection</h3><input id="source" class="text" placeholder="TV Source IP, e.g. 192.168.1.50"><p class="note">One portal controls both APKs. Low-latency binary WebSocket remains the normal light path.</p><button onclick="presetLow()">LOW LATENCY</button><button onclick="presetBalanced()">BALANCED</button></div>
<div class="card"><h3>TV Source</h3><div class="grid"><p>Target FPS <span id="sfpsv" class="v"></span><input id="sfps" type="range" min="4" max="30" step="1"></p><p>Samples / zone <span id="ssamplesv" class="v"></span><input id="ssamples" type="range" min="1" max="6"></p><p>Edge depth <span id="sstripv" class="v"></span><input id="sstrip" type="range" min=".03" max=".20" step=".01"></p><p><label><input id="sauto" class="toggle" type="checkbox"> Auto boot</label></p></div><p>Optional processed capture POST URL</p><input id="spush" class="text" placeholder="http://server/api/ambip"><p>Push FPS <span id="spushfpsv" class="v"></span><input id="spushfps" type="range" min="1" max="10" step="1"></p><p id="smeta" class="note"></p></div>
<div class="card"><h3>Motion / latency</h3><p><label><input id="interp" class="toggle" type="checkbox"> VSYNC interpolation</label></p><div class="grid"><p>Noise smoothing <span id="smoothv" class="v"></span><input id="smooth" type="range" min="0" max=".85" step=".01"></p><p>Catch-up ms <span id="interpmsv" class="v"></span><input id="interpms" type="range" min="0" max="140" step="2"></p><p>Fast response <span id="adaptivev" class="v"></span><input id="adaptive" type="range" min="0" max="1" step=".01"></p><p>Render Hz <span id="hzv" class="v"></span><input id="hz" type="range" min="30" max="120" step="1"></p></div></div>
<div class="card"><h3>Projector color calibration</h3><div class="grid"><p>Red gain <span id="rgainv" class="v"></span><input id="rgain" type="range" min=".4" max="2" step=".01"></p><p>Red offset <span id="roffv" class="v"></span><input id="roff" type="range" min="-80" max="80" step="1"></p><p>Green gain <span id="ggainv" class="v"></span><input id="ggain" type="range" min=".4" max="2" step=".01"></p><p>Green offset <span id="goffv" class="v"></span><input id="goff" type="range" min="-80" max="80" step="1"></p><p>Blue gain <span id="bgainv" class="v"></span><input id="bgain" type="range" min=".4" max="2" step=".01"></p><p>Blue offset <span id="boffv" class="v"></span><input id="boff" type="range" min="-80" max="80" step="1"></p></div><button onclick="resetRgb()">RESET RGB</button></div>
<div class="card"><h3>Light renderer</h3><select id="style" class="text"><option value="COLOR_CLOUD">Fast Color Cloud</option><option value="EDGE_GRADIENT">Edge Gradient</option></select><div class="grid">
<p>Brightness <span id="brightnessv" class="v"></span><input id="brightness" type="range" min=".4" max="1.8" step=".01"></p><p>Saturation <span id="saturationv" class="v"></span><input id="saturation" type="range" min=".5" max="2.5" step=".01"></p><p>Spread <span id="spreadv" class="v"></span><input id="spread" type="range" min=".05" max=".9" step=".01"></p><p>Radius <span id="radiusv" class="v"></span><input id="radius" type="range" min=".08" max=".5" step=".01"></p><p>Opacity <span id="opacityv" class="v"></span><input id="opacity" type="range" min=".05" max="1" step=".01"></p><p>Edge pull <span id="edgepullv" class="v"></span><input id="edgepull" type="range" min="0" max="1" step=".01"></p><p>Softness <span id="softnessv" class="v"></span><input id="softness" type="range" min="0" max="1" step=".01"></p><p>Outer fade <span id="fadev" class="v"></span><input id="fade" type="range" min=".02" max=".42" step=".01"></p><p>Corner blend <span id="cornerblendv" class="v"></span><input id="cornerblend" type="range" min="0" max="1" step=".01"></p><p>Corner radius <span id="cornerradiusv" class="v"></span><input id="cornerradius" type="range" min=".7" max="2.4" step=".02"></p><p>Dynamic amount <span id="dynamicv" class="v"></span><input id="dynamic" type="range" min="0" max="1.5" step=".01"></p><p>Dynamic radius <span id="dynradiusv" class="v"></span><input id="dynradius" type="range" min="0" max="1.5" step=".01"></p><p>Dynamic stretch <span id="stretchv" class="v"></span><input id="stretch" type="range" min="0" max="2" step=".01"></p><p>Dynamic opacity <span id="dynopacityv" class="v"></span><input id="dynopacity" type="range" min="0" max=".8" step=".01"></p><p>Energy curve <span id="energygammav" class="v"></span><input id="energygamma" type="range" min=".4" max="2.5" step=".01"></p><p>Saturation weight <span id="satweightv" class="v"></span><input id="satweight" type="range" min="0" max="1" step=".01"></p><p>Brightness weight <span id="lumaweightv" class="v"></span><input id="lumaweight" type="range" min="0" max="1" step=".01"></p><p>Cloud render scale <span id="cloudscalev" class="v"></span><input id="cloudscale" type="range" min=".2" max="1" step=".02"></p></div></div>
<div class="card"><h3>Projection geometry · drag directly</h3><p><label><input id="calibrate" class="toggle" type="checkbox"> Show calibration overlay on projector</label></p><svg id="geom" viewBox="0 0 1000 600"><g id="grid"></g><polygon id="outer" class="outer"></polygon><polygon id="tv" class="tv"></polygon><g id="textRects"></g><text x="24" y="35" class="label">OUTER</text><text id="tvlabel" class="label">TV</text><g id="handles"></g></svg><p class="note">Blue: outer projection. Green: TV mask — all four corners move freely. Orange: text zones — drag the box to move, drag corner dots to resize.</p><button onclick="resetOuter()">RESET OUTER</button><button onclick="resetTv()">RESET TV</button><button onclick="resetTextBoxes()">RESET TEXT BOXES</button></div>
<div class="card"><h3>Context text API</h3><div id="textControls"></div><p class="note">API: <code>POST /api/text-zone</code> with JSON or form fields <code>zone,text,durationMs</code>. Add <code>l,t,r,b</code> to reposition the box. <code>GET /api/text-zones</code> returns all zones.</p><button onclick="clearTexts()">CLEAR ALL TEXT</button></div>
<div class="card"><h3>TV capture API</h3><p class="note"><code>/api/capture/latest</code> is processed edge RGB data. Snapshot is a 128×72 JPEG generated only on request.</p><button onclick="loadCapture()">LOAD CAPTURE JSON</button><button onclick="takeSnapshot()">TAKE SNAPSHOT</button><pre id="capture" class="api"></pre><img id="shot" style="max-width:100%;border-radius:8px"></div>
<script>
const $=id=>document.getElementById(id);let cfg={},src={},timer,stimer,gtimer,drag=null,dragging=false;
const keys=['smooth','interpms','adaptive','hz','rgain','ggain','bgain','roff','goff','boff','brightness','saturation','spread','radius','opacity','edgepull','softness','fade','cornerblend','cornerradius','dynamic','dynradius','stretch','dynopacity','energygamma','satweight','lumaweight','cloudscale'];
function labels(){keys.forEach(k=>{let e=$(k+'v');if(e)e.textContent=$(k).value});$('sfpsv').textContent=$('sfps').value;$('ssamplesv').textContent=$('ssamples').value;$('sstripv').textContent=Number($('sstrip').value).toFixed(2);$('spushfpsv').textContent=$('spushfps').value}
function localQuery(){let q='source='+encodeURIComponent($('source').value)+'&interp='+($('interp').checked?1:0)+'&style='+$('style').value+'&calibrate='+($('calibrate').checked?1:0);keys.forEach(k=>q+='&'+k+'='+encodeURIComponent($(k).value));return q}
function saveLocal(){labels();clearTimeout(timer);timer=setTimeout(()=>fetch('/api/settings?'+localQuery()),45)}
function saveSource(){labels();clearTimeout(stimer);stimer=setTimeout(()=>fetch('/api/source/settings?fps='+$('sfps').value+'&samples='+$('ssamples').value+'&strip='+$('sstrip').value+'&autostart='+($('sauto').checked?1:0)+'&pushFps='+$('spushfps').value+'&pushUrl='+encodeURIComponent($('spush').value)),80)}
async function load(){try{cfg=await(await fetch('/api/status')).json();if(!dragging)applyCfg();$('pb').className='pill ok'}catch(e){$('pb').className='pill bad'}try{let wrap=await(await fetch('/api/source/status')).json();src=wrap.data||{};$('tb').textContent=wrap.reachable?(src.active?'TV LIVE':'TV IDLE'):'TV OFFLINE';$('tb').className='pill '+(wrap.reachable?'ok':'bad');$('rtt').textContent=wrap.reachable?(wrap.rttMs+' ms ctrl'):'—';$('smeta').textContent=wrap.reachable?((src.fpsActual||0)+' actual fps · '+(src.analysisW||0)+'×'+(src.analysisH||0)+' · '+(src.protocol||'')):(wrap.error||'unreachable');if(wrap.reachable&&!dragging){$('sfps').value=src.fps;$('ssamples').value=src.samples;$('sstrip').value=src.strip;$('sauto').checked=!!src.autostart;$('spush').value=src.pushUrl||'';$('spushfps').value=src.pushFps||2}}catch(e){$('tb').className='pill bad'}labels()}
function applyCfg(){$('source').value=cfg.source||'';$('interp').checked=!!cfg.interp;$('style').value=cfg.style||'COLOR_CLOUD';$('calibrate').checked=!!cfg.calibrate;keys.forEach(k=>{if(cfg[k]!==undefined)$(k).value=cfg[k]});drawGeom()}
function drawGrid(){let s='';for(let x=100;x<1000;x+=100)s+=`<line x1="${x}" y1="0" x2="${x}" y2="600" class="guide"/>`;for(let y=100;y<600;y+=100)s+=`<line x1="0" y1="${y}" x2="1000" y2="${y}" class="guide"/>`;$('grid').innerHTML=s}
function qp(prefix){let p=[];for(let i=0;i<8;i+=2)p.push([(cfg[prefix+i]??(prefix==='k'?[0,0,1,0,1,1,0,1][i]:[.2,.27,.8,.27,.8,.73,.2,.73][i]))*1000,(cfg[prefix+(i+1)]??(prefix==='k'?[0,0,1,0,1,1,0,1][i+1]:[.2,.27,.8,.27,.8,.73,.2,.73][i+1]))*600]);return p}
function drawGeom(){let o=qp('k'),t=qp('tq');$('outer').setAttribute('points',o.map(v=>v.join(',')).join(' '));$('tv').setAttribute('points',t.map(v=>v.join(',')).join(' '));$('tvlabel').setAttribute('x',t[0][0]+15);$('tvlabel').setAttribute('y',t[0][1]+30);let rects='',handles='';o.forEach((v,i)=>handles+=`<circle class="handleO" data-type="outer" data-i="${i}" cx="${v[0]}" cy="${v[1]}" r="15"/>`);t.forEach((v,i)=>handles+=`<circle class="handleT" data-type="tv" data-i="${i}" cx="${v[0]}" cy="${v[1]}" r="15"/>`);for(let z=0;z<4;z++){let l=(cfg[`tf${z}_0`]??[.24,.24,.03,.82][z])*1000,tt=(cfg[`tf${z}_1`]??[.06,.82,.32,.32][z])*600,r=(cfg[`tf${z}_2`]??[.76,.76,.18,.97][z])*1000,b=(cfg[`tf${z}_3`]??[.18,.94,.68,.68][z])*600;rects+=`<rect class="textBox" data-type="textmove" data-z="${z}" x="${l}" y="${tt}" width="${r-l}" height="${b-tt}" rx="8"/><text class="label" x="${l+10}" y="${tt+26}">${['TOP','BOTTOM','LEFT','RIGHT'][z]}</text>`;[[l,tt],[r,tt],[r,b],[l,b]].forEach((v,i)=>handles+=`<circle class="handleX" data-type="texthandle" data-z="${z}" data-i="${i}" cx="${v[0]}" cy="${v[1]}" r="10"/>`)}$('textRects').innerHTML=rects;$('handles').innerHTML=handles}
function point(ev){let r=$('geom').getBoundingClientRect();return[Math.max(0,Math.min(1,(ev.clientX-r.left)/r.width)),Math.max(0,Math.min(1,(ev.clientY-r.top)/r.height))]}
function down(ev){let t=ev.target;if(!t.dataset.type)return;let [x,y]=point(ev);drag={type:t.dataset.type,i:+(t.dataset.i||0),z:+(t.dataset.z||0),sx:x,sy:y};if(drag.type==='textmove')drag.box=[+cfg[`tf${drag.z}_0`],+cfg[`tf${drag.z}_1`],+cfg[`tf${drag.z}_2`],+cfg[`tf${drag.z}_3`]];dragging=true;$('geom').setPointerCapture(ev.pointerId);ev.preventDefault()}
function move(ev){if(!drag)return;let [x,y]=point(ev);if(drag.type==='outer'||drag.type==='tv'){let p=drag.type==='outer'?'k':'tq',j=drag.i*2;cfg[p+j]=x;cfg[p+(j+1)]=y}else if(drag.type==='textmove'){let z=drag.z,b=drag.box,w=b[2]-b[0],h=b[3]-b[1],dx=x-drag.sx,dy=y-drag.sy,l=Math.max(0,Math.min(1-w,b[0]+dx)),t=Math.max(0,Math.min(1-h,b[1]+dy));cfg[`tf${z}_0`]=l;cfg[`tf${z}_1`]=t;cfg[`tf${z}_2`]=l+w;cfg[`tf${z}_3`]=t+h}else{let z=drag.z,l=+cfg[`tf${z}_0`],t=+cfg[`tf${z}_1`],r=+cfg[`tf${z}_2`],b=+cfg[`tf${z}_3`],i=drag.i;if(i===0||i===3)l=Math.min(x,r-.04);else r=Math.max(x,l+.04);if(i===0||i===1)t=Math.min(y,b-.04);else b=Math.max(y,t+.04);cfg[`tf${z}_0`]=l;cfg[`tf${z}_1`]=t;cfg[`tf${z}_2`]=r;cfg[`tf${z}_3`]=b}drawGeom();saveGeometry();ev.preventDefault()}
function up(){drag=null;setTimeout(()=>dragging=false,120)}
function saveGeometry(){clearTimeout(gtimer);gtimer=setTimeout(()=>{let q='';for(let i=0;i<8;i++)q+=(q?'&':'')+`k${i}=${cfg['k'+i]}&tq${i}=${cfg['tq'+i]}`;for(let z=0;z<4;z++)for(let i=0;i<4;i++)q+=`&tf${z}_${i}=${cfg[`tf${z}_${i}`]}`;fetch('/api/settings?'+q)},35)}
function resetOuter(){[0,0,1,0,1,1,0,1].forEach((v,i)=>cfg['k'+i]=v);drawGeom();saveGeometry()}function resetTv(){[.2,.27,.8,.27,.8,.73,.2,.73].forEach((v,i)=>cfg['tq'+i]=v);drawGeom();saveGeometry()}function resetTextBoxes(){let d=[[.24,.06,.76,.18],[.24,.82,.76,.94],[.03,.32,.18,.68],[.82,.32,.97,.68]];for(let z=0;z<4;z++)for(let i=0;i<4;i++)cfg[`tf${z}_${i}`]=d[z][i];drawGeom();saveGeometry()}
function resetRgb(){['rgain','ggain','bgain'].forEach(x=>$(x).value=1);['roff','goff','boff'].forEach(x=>$(x).value=0);saveLocal()}
function presetLow(){$('smooth').value=.08;$('interpms').value=24;$('adaptive').value=.98;$('hz').value=60;$('sfps').value=12;$('ssamples').value=1;saveLocal();saveSource()}function presetBalanced(){$('smooth').value=.14;$('interpms').value=32;$('adaptive').value=.94;$('hz').value=60;$('sfps').value=10;$('ssamples').value=2;saveLocal();saveSource()}
function buildTextControls(){let names=['TOP','BOTTOM','LEFT','RIGHT'],h='';for(let z=0;z<4;z++)h+=`<div class="grid"><p><b>${names[z]}</b><textarea id="zt${z}" rows="2" placeholder="Text for ${names[z]}"></textarea></p><p>Duration ms<input id="zd${z}" class="text" type="number" value="5000" min="0"><button onclick="sendText(${z})">SHOW</button><button onclick="clearText(${z})">CLEAR</button></p></div>`;$('textControls').innerHTML=h}
async function sendText(z){let body=new URLSearchParams({zone:String(z),text:$('zt'+z).value,durationMs:$('zd'+z).value});await fetch('/api/text-zone',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});}async function clearText(z){await fetch('/api/text-zone?zone='+z+'&clear=1')}async function clearTexts(){await fetch('/api/text-zones/clear')}
async function loadCapture(){try{let x=await(await fetch('/api/source/capture/latest')).json();$('capture').textContent=JSON.stringify(x,null,2)}catch(e){$('capture').textContent='Capture API unavailable'}}function takeSnapshot(){$('shot').src='/api/source/snapshot.jpg?t='+Date.now()}
drawGrid();buildTextControls();$('geom').addEventListener('pointerdown',down);$('geom').addEventListener('pointermove',move);$('geom').addEventListener('pointerup',up);$('geom').addEventListener('pointercancel',up);keys.forEach(k=>$(k).oninput=saveLocal);$('interp').onchange=saveLocal;$('style').onchange=saveLocal;$('calibrate').onchange=saveLocal;$('source').onchange=saveLocal;['sfps','ssamples','sstrip','spushfps'].forEach(k=>$(k).oninput=saveSource);$('sauto').onchange=saveSource;$('spush').onchange=saveSource;load();setInterval(load,1600);
</script></body></html>
""";
}
